### ISSUE TITLE
[console] Clean up output code

### ISSUE THREAD

**Issue by damienmckenna** [hechoendrupal/DrupalAppConsole#447] opened 2015-02-24 02:03 UTC
The code output from the generators is inconsistent and does not appear to match the Drupal coding standards (https://www.drupal.org/coding-standards) very well.

**Comment by jmolivas** [comment] 2015-02-24 03:35
We just finishing implementing PSR-2 a code clean on the project code #400, next step is to make generated code fully complaint with Drupal coding standards.

Thanks for  testing the project and provide feedback @damienmckenna

**Comment by chipkaye** [comment] 2015-02-25 17:47
Beginning work on this issue.

**Comment by dmouse** [comment] 2015-03-02 00:50
in this PR #475 I am test the commands into a drupal installation and I check the code standards.
I'll wait to merge my PR for some PRs to solve these bugs 

https://travis-ci.org/hechoendrupal/DrupalAppConsole/jobs/52679745#L628

**Comment by dmouse** [comment] 2015-03-02 20:19
this is the result after to apply your PR @chipkaye.

there are still a few bugs
https://travis-ci.org/hechoendrupal/DrupalAppConsole/jobs/52793120#L628

**Comment by chipkaye** [comment] 2015-03-02 21:12
@dmouse - I'm unable to reproduce the errors shown for travis-entity.page.inc and TravisEntityConfigForm.php - both run clean through phpcs on my local.  The errors shown for TravisEntityConfigForm.php in particular look suspect - i.e. references to "-".  Take a look at templates/module/src/Form/entity.php.twig to see the corresponding template.

The errors for TravisRestResource.php are due to an incomplete function - see my commit message at 1979eb5e2afca45.  Thoughts?

The two warnings are for long pathnames which create lines > 80 chars.  Thoughts?

**Comment by jmolivas** [comment] 2015-03-04 01:30
@chipkaye @dmouse How about add some docs to execute phpcs on local, to make easy to validate code prior to commit and/or push code and send a PR.

**Comment by chipkaye** [comment] 2015-03-04 02:15
@jmolivas - sure.  where do you think the docs should go?

**Comment by jmolivas** [comment] 2015-03-04 06:54
@chipkaye at the console-book documentation, adding a new page to the how-to-contribute section: 
http://hechoendrupal.gitbooks.io/drupal-console/content/how-to-contribute/project-requirements.html

**Comment by dmouse** [comment] 2015-03-08 18:50
@chipkaye sorry for the delay, I created some scripts to probe commands, in my PR you only need run this scripts into a drupal installation.

```bash
drupal8.dev $ bash ~/public_html/www/DrupalAppConsole/Test/script/test-generation-commands.sh
```

I'm fixed all errors in the generated code
https://travis-ci.org/hechoendrupal/DrupalAppConsole/jobs/53494138#L628

@jmolivas sure maybe you can helpme to write this instructions for the "development" section to gitbook

**Comment by jmolivas** [comment] 2015-03-08 19:27
@dmouse sure I can help but have no idea what the instructions are

**Comment by dmouse** [comment] 2015-03-09 05:07
Sure, into your drupal installation run the follow commands
```bash 
$ composer global require drupal/coder:~8.1
$ bash ~/DrupaAppConsole/Test/script/test-generation-commands.sh
$ ~/.composer/vendor/bin/phpcs --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml modules/custom/travis
```

The PR has merged I am close this issue

**Closed by dmouse** 2015-03-09 05:07 UTC
Labels: bug
